-- #225 (epic #168): the SQL progress model equals the shared fixture
-- test/fixtures/tracking_progress_vectors.json (features/11 section 3).
-- GENERATED by tool/tracking/generate_vectors_sql.py; test/features/tracking/tracking_vectors_sql_parity_test.dart fails if they drift.
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;

SELECT plan(11);

INSERT INTO auth.users (id, email) VALUES ('f3500000-0000-0000-0000-000000000001', 'vectors@tracking.dev');

-- ended_two_seasons: Ended series, 2 seasons (9 + 10), every episode aired, episodes cached.
INSERT INTO public.titles (id, media_type, title, status) VALUES (9100001, 'tv', 'ended_two_seasons', 'Ended');
INSERT INTO public.tv_seasons (title_id, season_number, episode_count, air_date) VALUES (9100001, 1, 9, '2022-02-18');
INSERT INTO public.tv_seasons (title_id, season_number, episode_count, air_date) VALUES (9100001, 2, 10, '2025-01-17');
INSERT INTO public.tv_episodes (title_id, season_number, episode_number, air_date) SELECT 9100001, 1, n, DATE '2022-02-18' + (n - 1) * 7 FROM generate_series(1, 9) AS g(n);
INSERT INTO public.tv_episodes (title_id, season_number, episode_number, air_date) SELECT 9100001, 2, n, DATE '2025-01-17' + (n - 1) * 7 FROM generate_series(1, 10) AS g(n);

-- running_weekly: Returning series mid-season: S2 E1-E4 aired, E5-E10 not yet.
INSERT INTO public.titles (id, media_type, title, status) VALUES (9100002, 'tv', 'running_weekly', 'Returning Series');
INSERT INTO public.tv_seasons (title_id, season_number, episode_count, air_date) VALUES (9100002, 1, 8, '2024-02-27');
INSERT INTO public.tv_seasons (title_id, season_number, episode_count, air_date) VALUES (9100002, 2, 10, '2026-09-18');
INSERT INTO public.tv_episodes (title_id, season_number, episode_number, air_date) SELECT 9100002, 1, n, DATE '2024-02-27' + (n - 1) * 7 FROM generate_series(1, 8) AS g(n);
INSERT INTO public.tv_episodes (title_id, season_number, episode_number, air_date) SELECT 9100002, 2, n, DATE '2026-09-18' + (n - 1) * 7 FROM generate_series(1, 10) AS g(n);

-- no_episode_cache_running: Returning series with no tv_episodes rows: season fallback applies, and the latest season of a running show counts as unaired.
INSERT INTO public.titles (id, media_type, title, status) VALUES (9100003, 'tv', 'no_episode_cache_running', 'Returning Series');
INSERT INTO public.tv_seasons (title_id, season_number, episode_count, air_date) VALUES (9100003, 1, 6, '2025-06-01');
INSERT INTO public.tv_seasons (title_id, season_number, episode_count, air_date) VALUES (9100003, 2, 6, '2026-09-01');

-- no_episode_cache_ended: Ended series with no tv_episodes rows: every started season counts as aired.
INSERT INTO public.titles (id, media_type, title, status) VALUES (9100004, 'tv', 'no_episode_cache_ended', 'Ended');
INSERT INTO public.tv_seasons (title_id, season_number, episode_count, air_date) VALUES (9100004, 1, 6, '2021-03-05');
INSERT INTO public.tv_seasons (title_id, season_number, episode_count, air_date) VALUES (9100004, 2, 7, '2022-03-04');

-- unknown_air_dates: Announced season with no air date anywhere: nothing in it has aired.
INSERT INTO public.titles (id, media_type, title, status) VALUES (9100005, 'tv', 'unknown_air_dates', 'Returning Series');
INSERT INTO public.tv_seasons (title_id, season_number, episode_count, air_date) VALUES (9100005, 1, 8, '2023-01-15');
INSERT INTO public.tv_seasons (title_id, season_number, episode_count, air_date) VALUES (9100005, 2, 8, NULL);
INSERT INTO public.tv_episodes (title_id, season_number, episode_number, air_date) SELECT 9100005, 1, n, DATE '2023-01-15' + (n - 1) * 7 FROM generate_series(1, 8) AS g(n);
INSERT INTO public.tv_episodes (title_id, season_number, episode_number, air_date) SELECT 9100005, 2, n, NULL FROM generate_series(1, 8) AS g(n);

-- single_season_ended: Limited series, one season of 10, all aired.
INSERT INTO public.titles (id, media_type, title, status) VALUES (9100006, 'tv', 'single_season_ended', 'Ended');
INSERT INTO public.tv_seasons (title_id, season_number, episode_count, air_date) VALUES (9100006, 1, 10, '2024-02-27');
INSERT INTO public.tv_episodes (title_id, season_number, episode_number, air_date) SELECT 9100006, 1, n, DATE '2024-02-27' + (n - 1) * 7 FROM generate_series(1, 10) AS g(n);

INSERT INTO public.titles (id, media_type, title) VALUES (9100100, 'movie', 'vector movie');

SELECT is_empty(
    $$ SELECT v.name, c.clamped_season, c.clamped_episode, n.next_season, n.next_episode,
              public._tracking_state(v.title_id, 'tv', c.clamped_season, c.clamped_episode, NULL, DATE '2026-10-09') AS state
       FROM (VALUES
    ('not started, ended show', 9100001, NULL::INT, NULL::INT, NULL::INT, NULL::INT, 1, 1, 'WATCHING'),
    ('mid season', 9100001, 2, 5, 2, 5, 2, 6, 'WATCHING'),
    ('season boundary: last episode of S1', 9100001, 1, 9, 1, 9, 2, 1, 'WATCHING'),
    ('last episode of an ended show', 9100001, 2, 10, 2, 10, NULL::INT, NULL::INT, 'FINISHED'),
    ('caught up on a running show', 9100002, 2, 4, 2, 4, NULL::INT, NULL::INT, 'CAUGHT_UP'),
    ('behind on a running show', 9100002, 2, 1, 2, 1, 2, 2, 'WATCHING'),
    ('episode cache missing: latest season of a running show is unaired', 9100003, 1, 6, 1, 6, NULL::INT, NULL::INT, 'CAUGHT_UP'),
    ('episode cache missing on an ended show: season fallback airs everything', 9100004, 1, 6, 1, 6, 2, 1, 'WATCHING'),
    ('unknown air dates never air', 9100005, 1, 8, 1, 8, NULL::INT, NULL::INT, 'CAUGHT_UP'),
    ('place past the season count is clamped', 9100006, 1, 14, 1, 10, NULL::INT, NULL::INT, 'FINISHED'),
    ('place in a season that no longer exists is clamped to the last season', 9100006, 3, 2, 1, 10, NULL::INT, NULL::INT, 'FINISHED'),
    ('not started on a limited series', 9100006, NULL::INT, NULL::INT, NULL::INT, NULL::INT, 1, 1, 'WATCHING')
       ) AS v(name, title_id, ps, pe, cs, ce, ns, ne, state)
       CROSS JOIN LATERAL public._tracking_clamp(v.title_id, v.ps, v.pe) AS c
       LEFT JOIN LATERAL public._tracking_next(v.title_id, c.clamped_season, c.clamped_episode, DATE '2026-10-09') AS n ON TRUE
       WHERE c.clamped_season IS DISTINCT FROM v.cs
          OR c.clamped_episode IS DISTINCT FROM v.ce
          OR n.next_season IS DISTINCT FROM v.ns
          OR n.next_episode IS DISTINCT FROM v.ne
          OR public._tracking_state(v.title_id, 'tv', c.clamped_season, c.clamped_episode, NULL, DATE '2026-10-09')::TEXT <> v.state $$,
    'clamp, next episode and state match all 12 fixture vectors'
);

SELECT is(public._tracking_state(9100100, 'movie', NULL, NULL, NULL, DATE '2026-10-09')::TEXT, 'WATCHING', 'movie: movie in progress');
SELECT is(public._tracking_state(9100100, 'movie', NULL, NULL, TIMESTAMPTZ '2026-10-06', DATE '2026-10-09')::TEXT, 'FINISHED', 'movie: movie finished');

CREATE FUNCTION pg_temp.move_events(p_title INT, p_fs INT, p_fe INT, p_ts INT, p_te INT) RETURNS TEXT
LANGUAGE plpgsql AS $f$
DECLARE
    v_row public.user_tracking;
    v_out TEXT;
BEGIN
    DELETE FROM public.user_tracking_events WHERE user_id = 'f3500000-0000-0000-0000-000000000001' AND title_id = p_title;
    DELETE FROM public.user_tracking WHERE user_id = 'f3500000-0000-0000-0000-000000000001' AND title_id = p_title;
    INSERT INTO public.user_tracking (user_id, title_id, media_type, last_season, last_episode, state)
    VALUES ('f3500000-0000-0000-0000-000000000001', p_title, 'tv', p_fs, p_fe, 'WATCHING');
    SELECT * INTO v_row FROM public.user_tracking WHERE user_id = 'f3500000-0000-0000-0000-000000000001' AND title_id = p_title;
    PERFORM public._tracking_move(v_row, p_ts, p_te);
    SELECT COALESCE(string_agg(kind || ' S' || season_number || 'E' || episode_number, ', '
                              ORDER BY season_number, episode_number), '')
      INTO v_out FROM public.user_tracking_events
     WHERE user_id = 'f3500000-0000-0000-0000-000000000001' AND title_id = p_title;
    RETURN v_out;
END $f$;

SELECT is(pg_temp.move_events(9100001, 2, 5, 2, 6), 'WATCHED S2E6', 'events: forward one episode');
SELECT is(pg_temp.move_events(9100001, 1, 9, 2, 1), 'WATCHED S2E1', 'events: forward across a season boundary');
SELECT is(pg_temp.move_events(9100001, 2, 5, 2, 8), 'WATCHED S2E6, WATCHED S2E7, WATCHED S2E8', 'events: jump forward three');
SELECT is(pg_temp.move_events(9100001, NULL::INT, NULL::INT, 1, 2), 'WATCHED S1E1, WATCHED S1E2', 'events: start from nothing to S1 E2');
SELECT is(pg_temp.move_events(9100001, 2, 6, 2, 5), 'UNWATCHED S2E6', 'events: un-log one episode');
SELECT is(pg_temp.move_events(9100001, 2, 1, 1, 8), 'UNWATCHED S1E9, UNWATCHED S2E1', 'events: un-log back across a season boundary');
SELECT is(pg_temp.move_events(9100006, 1, 2, NULL::INT, NULL::INT), 'UNWATCHED S1E1, UNWATCHED S1E2', 'events: un-log everything');
SELECT is(pg_temp.move_events(9100001, 2, 6, 2, 6), '', 'events: no move, no events');

SELECT * FROM finish();
ROLLBACK;
