"""Keep every agent's instructions identical.

Sources of truth (edit only these):
  AGENTS.md          rules for all agents
  .agents/skills/    skills for all agents

Generated (never edit by hand):
  CLAUDE.md, GEMINI.md   copies of AGENTS.md with a banner
  .claude/skills/        exact mirror of .agents/skills/

  python tool/agents/sync.py           # regenerate
  python tool/agents/sync.py --check   # CI: exit 1 if anything drifted
"""

import argparse
import pathlib
import re
import shutil
import sys

ROOT = pathlib.Path(__file__).resolve().parents[2]
SOURCE_RULES = ROOT / "AGENTS.md"
RULE_COPIES = [ROOT / "CLAUDE.md", ROOT / "GEMINI.md"]
SOURCE_SKILLS = ROOT / ".agents" / "skills"
SKILL_MIRRORS = [ROOT / ".claude" / "skills"]
BANNER = ("<!-- GENERATED from AGENTS.md by tool/agents/sync.py. Do not edit this file: "
          "edit AGENTS.md and run `python tool/agents/sync.py`. -->\n\n")


def norm(data: bytes) -> bytes:
    return data.replace(b"\r\n", b"\n")


def expected_rules() -> bytes:
    return BANNER.encode() + norm(SOURCE_RULES.read_bytes())


def skill_files(base: pathlib.Path):
    return {p.relative_to(base).as_posix(): p for p in base.rglob("*") if p.is_file()}


def validate_skills():
    problems = []
    for folder in sorted(p for p in SOURCE_SKILLS.iterdir() if p.is_dir()):
        skill = folder / "SKILL.md"
        if not skill.exists():
            problems.append(f"{folder.name}: missing SKILL.md")
            continue
        head = skill.read_text(encoding="utf-8").split("---")
        meta = head[1] if len(head) > 2 else ""
        name = re.search(r"^name:\s*(\S+)", meta, re.M)
        if not name or name.group(1) != folder.name:
            problems.append(f"{folder.name}: frontmatter name must equal the folder name")
        if not re.search(r"^description:", meta, re.M):
            problems.append(f"{folder.name}: frontmatter needs a description (it decides when the skill is used)")
    return problems


def drift():
    problems = validate_skills()
    for copy in RULE_COPIES:
        if not copy.exists() or norm(copy.read_bytes()) != expected_rules():
            problems.append(f"{copy.name} differs from AGENTS.md")
    src = skill_files(SOURCE_SKILLS)
    for mirror in SKILL_MIRRORS:
        dst = skill_files(mirror) if mirror.exists() else {}
        for rel, path in src.items():
            if rel not in dst:
                problems.append(f"{mirror.relative_to(ROOT).as_posix()}/{rel} missing")
            elif norm(dst[rel].read_bytes()) != norm(path.read_bytes()):
                problems.append(f"{mirror.relative_to(ROOT).as_posix()}/{rel} differs")
        for rel in dst.keys() - src.keys():
            problems.append(f"{mirror.relative_to(ROOT).as_posix()}/{rel} has no source in .agents/skills")
    return problems


def write():
    for copy in RULE_COPIES:
        copy.write_bytes(expected_rules())
    # File by file rather than rmtree: editors on Windows hold skill folders open.
    src = skill_files(SOURCE_SKILLS)
    for mirror in SKILL_MIRRORS:
        dst = skill_files(mirror) if mirror.exists() else {}
        for rel, path in src.items():
            target = mirror / rel
            if rel not in dst or norm(dst[rel].read_bytes()) != norm(path.read_bytes()):
                target.parent.mkdir(parents=True, exist_ok=True)
                shutil.copyfile(path, target)
        for rel in dst.keys() - src.keys():
            dst[rel].unlink()
        for folder in sorted((p for p in mirror.rglob("*") if p.is_dir()), key=lambda p: -len(p.parts)):
            if not any(folder.iterdir()):
                folder.rmdir()


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--check", action="store_true")
    args = p.parse_args()
    if args.check:
        problems = drift()
        for line in problems:
            print(f"drift: {line}")
        if problems:
            print("Run `python tool/agents/sync.py` after editing AGENTS.md or .agents/skills/.")
            sys.exit(1)
        print("agent instructions in sync")
        return
    invalid = validate_skills()
    if invalid:
        sys.exit("\n".join(invalid))
    write()
    print("CLAUDE.md, GEMINI.md and .claude/skills regenerated from AGENTS.md and .agents/skills")


if __name__ == "__main__":
    main()
