#!/usr/bin/env python3
"""Generates supabase/tests/database/035_tracking_progress_vectors.test.sql from
test/fixtures/tracking_progress_vectors.json (#225, features/11 section 3).

    python tool/tracking/generate_vectors_sql.py

test/features/tracking/tracking_vectors_sql_parity_test.dart fails when the generated file
stops embedding every vector, so rerun this after editing the fixture.
"""
import json
import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[2]
FIXTURE = ROOT / "test" / "fixtures" / "tracking_progress_vectors.json"
OUT = ROOT / "supabase" / "tests" / "database" / "035_tracking_progress_vectors.test.sql"

USER = "f3500000-0000-0000-0000-000000000001"
BASE_ID = 9100001
MOVIE_ID = 9100100


def q(text: str) -> str:
    return "'" + text.replace("'", "''") + "'"


def num(value) -> str:
    return "NULL::INT" if value is None else str(value)


def main() -> None:
    fx = json.loads(FIXTURE.read_text(encoding="utf-8"))
    today = fx["today"]
    shows = fx["shows"]
    ids = {key: BASE_ID + i for i, key in enumerate(shows)}

    lines = [
        "-- #225 (epic #168): the SQL progress model equals the shared fixture",
        "-- test/fixtures/tracking_progress_vectors.json (features/11 section 3).",
        "-- GENERATED by tool/tracking/generate_vectors_sql.py; "
        "test/features/tracking/tracking_vectors_sql_parity_test.dart fails if they drift.",
        "BEGIN;",
        "CREATE EXTENSION IF NOT EXISTS pgtap WITH SCHEMA extensions;",
        "",
    ]

    state_vectors = fx["vectors"]
    movie_vectors = fx["movie_vectors"]
    event_vectors = fx["event_vectors"]
    plan = 1 + len(movie_vectors) + len(event_vectors)
    lines += [f"SELECT plan({plan});", ""]

    lines += [f"INSERT INTO auth.users (id, email) VALUES ('{USER}', 'vectors@tracking.dev');", ""]

    # Titles, seasons and cached episodes.
    for key, show in shows.items():
        tid = ids[key]
        lines.append(f"-- {key}: {show['description']}")
        lines.append(
            f"INSERT INTO public.titles (id, media_type, title, status) VALUES ({tid}, 'tv', {q(key)}, {q(show['status'])});"
        )
        for s in show["seasons"]:
            air = "NULL" if s["air_date"] is None else q(s["air_date"])
            lines.append(
                f"INSERT INTO public.tv_seasons (title_id, season_number, episode_count, air_date) "
                f"VALUES ({tid}, {s['number']}, {s['episode_count']}, {air});"
            )
        for r in show["episodes"]:
            first = r["first_air_date"]
            air = "NULL" if first is None else f"DATE {q(first)} + (n - {r['from']}) * {r['interval_days']}"
            lines.append(
                f"INSERT INTO public.tv_episodes (title_id, season_number, episode_number, air_date) "
                f"SELECT {tid}, {r['season']}, n, {air} FROM generate_series({r['from']}, {r['to']}) AS g(n);"
            )
        lines.append("")
    lines.append(
        f"INSERT INTO public.titles (id, media_type, title) VALUES ({MOVIE_ID}, 'movie', 'vector movie');"
    )
    lines.append("")

    # State, next episode and clamp.
    rows = []
    for v in state_vectors:
        place = v["place"]
        clamped = v.get("clamped_place", place)
        nxt = v["next"]
        rows.append(
            "    ({name}, {tid}, {ps}, {pe}, {cs}, {ce}, {ns}, {ne}, {state})".format(
                name=q(v["name"]),
                tid=ids[v["show"]],
                ps=num(place["season"] if place else None),
                pe=num(place["episode"] if place else None),
                cs=num(clamped["season"] if clamped else None),
                ce=num(clamped["episode"] if clamped else None),
                ns=num(nxt["season"] if nxt else None),
                ne=num(nxt["episode"] if nxt else None),
                state=q(v["state"]),
            )
        )
    lines += [
        "SELECT is_empty(",
        "    $$ SELECT v.name, c.clamped_season, c.clamped_episode, n.next_season, n.next_episode,",
        f"              public._tracking_state(v.title_id, 'tv', c.clamped_season, c.clamped_episode, NULL, DATE '{today}') AS state",
        "       FROM (VALUES",
        ",\n".join(rows),
        "       ) AS v(name, title_id, ps, pe, cs, ce, ns, ne, state)",
        "       CROSS JOIN LATERAL public._tracking_clamp(v.title_id, v.ps, v.pe) AS c",
        f"       LEFT JOIN LATERAL public._tracking_next(v.title_id, c.clamped_season, c.clamped_episode, DATE '{today}') AS n ON TRUE",
        "       WHERE c.clamped_season IS DISTINCT FROM v.cs",
        "          OR c.clamped_episode IS DISTINCT FROM v.ce",
        "          OR n.next_season IS DISTINCT FROM v.ns",
        "          OR n.next_episode IS DISTINCT FROM v.ne",
        f"          OR public._tracking_state(v.title_id, 'tv', c.clamped_season, c.clamped_episode, NULL, DATE '{today}')::TEXT <> v.state $$,",
        f"    'clamp, next episode and state match all {len(state_vectors)} fixture vectors'",
        ");",
        "",
    ]

    # Movies.
    for v in movie_vectors:
        fin = "NULL" if v["finished_at"] is None else f"TIMESTAMPTZ {q(v['finished_at'])}"
        lines.append(
            f"SELECT is(public._tracking_state({MOVIE_ID}, 'movie', NULL, NULL, {fin}, DATE '{today}')::TEXT, "
            f"{q(v['state'])}, {q('movie: ' + v['name'])});"
        )
    lines.append("")

    # Episode events, by moving the place with _tracking_move (a SECURITY DEFINER helper).
    lines += [
        "CREATE FUNCTION pg_temp.move_events(p_title INT, p_fs INT, p_fe INT, p_ts INT, p_te INT) RETURNS TEXT",
        "LANGUAGE plpgsql AS $f$",
        "DECLARE",
        "    v_row public.user_tracking;",
        "    v_out TEXT;",
        "BEGIN",
        f"    DELETE FROM public.user_tracking_events WHERE user_id = '{USER}' AND title_id = p_title;",
        f"    DELETE FROM public.user_tracking WHERE user_id = '{USER}' AND title_id = p_title;",
        "    INSERT INTO public.user_tracking (user_id, title_id, media_type, last_season, last_episode, state)",
        f"    VALUES ('{USER}', p_title, 'tv', p_fs, p_fe, 'WATCHING');",
        f"    SELECT * INTO v_row FROM public.user_tracking WHERE user_id = '{USER}' AND title_id = p_title;",
        "    PERFORM public._tracking_move(v_row, p_ts, p_te);",
        "    SELECT COALESCE(string_agg(kind || ' S' || season_number || 'E' || episode_number, ', '",
        "                              ORDER BY season_number, episode_number), '')",
        "      INTO v_out FROM public.user_tracking_events",
        f"     WHERE user_id = '{USER}' AND title_id = p_title;",
        "    RETURN v_out;",
        "END $f$;",
        "",
    ]
    for v in event_vectors:
        frm, to = v["from"], v["to"]
        expected = ", ".join(f"{e['kind']} S{e['season']}E{e['episode']}" for e in v["events"])
        lines.append(
            "SELECT is(pg_temp.move_events({tid}, {fs}, {fe}, {ts}, {te}), {exp}, {name});".format(
                tid=ids[v["show"]],
                fs=num(frm["season"] if frm else None),
                fe=num(frm["episode"] if frm else None),
                ts=num(to["season"] if to else None),
                te=num(to["episode"] if to else None),
                exp=q(expected),
                name=q("events: " + v["name"]),
            )
        )

    lines += ["", "SELECT * FROM finish();", "ROLLBACK;", ""]
    OUT.write_text("\n".join(lines), encoding="utf-8", newline="\n")
    print(f"wrote {OUT.relative_to(ROOT)} (plan {plan})")


if __name__ == "__main__":
    main()
