// Turns the app theme into the site's tokens.css (WEB-01).
// Spec: docs/design_system/01_DESIGN_PHILOSOPHY_AND_STYLE_GUIDE.md §2–§3.

/// A dark-mode color constant from `TellyColors`.
class ColorToken {
  final String name;
  final int argb;
  const ColorToken(this.name, this.argb);

  int get alpha => (argb >> 24) & 0xFF;
  int get red => (argb >> 16) & 0xFF;
  int get green => (argb >> 8) & 0xFF;
  int get blue => argb & 0xFF;

  /// `#rrggbb` when opaque, otherwise `rgba(r, g, b, a)`.
  String get css {
    if (alpha == 0xFF) {
      return '#${[red, green, blue].map((c) => c.toRadixString(16).padLeft(2, '0')).join()}';
    }
    return 'rgba($red, $green, $blue, ${_trim(alpha / 255, 3)})';
  }
}

/// A `TellyTypography` style, as read from the live `TextStyle`.
class TypeToken {
  final String name;
  final String family;
  final double size;
  final int weight;

  /// Line height as a multiple of [size]; null when the style leaves it to the font.
  final double? height;

  /// Tracking in logical pixels, as Flutter stores it.
  final double letterSpacing;
  final bool tabularFigures;

  const TypeToken({
    required this.name,
    required this.family,
    required this.size,
    required this.weight,
    this.height,
    this.letterSpacing = 0,
    this.tabularFigures = false,
  });

  Map<String, Object?> toJson() => {
        'name': name,
        'family': family,
        'size': size,
        'weight': weight,
        'height': height,
        'letterSpacing': letterSpacing,
        'tabularFigures': tabularFigures,
      };

  factory TypeToken.fromJson(Map<String, Object?> json) => TypeToken(
        name: json['name']! as String,
        family: json['family']! as String,
        size: (json['size']! as num).toDouble(),
        weight: json['weight']! as int,
        height: (json['height'] as num?)?.toDouble(),
        letterSpacing: (json['letterSpacing'] as num?)?.toDouble() ?? 0,
        tabularFigures: json['tabularFigures'] as bool? ?? false,
      );
}

/// A bundled font file (`assets/fonts/<Family>-<Weight>.ttf`).
class FontFace {
  final String family;
  final int weight;
  final String fileName;
  const FontFace(this.family, this.weight, this.fileName);
}

const Map<String, int> fontWeightNames = {
  'Thin': 100,
  'ExtraLight': 200,
  'Light': 300,
  'Regular': 400,
  'Medium': 500,
  'SemiBold': 600,
  'Bold': 700,
  'ExtraBold': 800,
  'Black': 900,
};

final _colorPattern = RegExp(r'static\s+const\s+Color\s+(\w+)\s*=\s*Color\(\s*0x([0-9A-Fa-f]{8})\s*\)');

/// Every `static const Color name = Color(0xAARRGGBB)` in [dartSource], minus
/// the Day Cathode (`light*`) tokens: the site is dark only.
List<ColorToken> parseColorTokens(String dartSource) => [
      for (final m in _colorPattern.allMatches(dartSource))
        if (!m.group(1)!.startsWith('light')) ColorToken(m.group(1)!, int.parse(m.group(2)!, radix: 16)),
    ];

/// The public style names declared in `telly_typography.dart`.
List<String> parseTypographyStyleNames(String dartSource) => [
      for (final m in RegExp(r'static\s+TextStyle\s+(\w+)\s*\(').allMatches(dartSource))
        if (!m.group(1)!.startsWith('_')) m.group(1)!,
    ];

/// `PlusJakartaSans-SemiBold.ttf` → (PlusJakartaSans, 600); null for other files.
FontFace? parseFontFile(String fileName) {
  final m = RegExp(r'^(\w+)-(\w+)\.ttf$').firstMatch(fileName);
  final weight = m == null ? null : fontWeightNames[m.group(2)];
  return weight == null ? null : FontFace(m!.group(1)!, weight, fileName);
}

/// `phosphorLime` → `phosphor-lime`, `displayXXL` → `display-xxl`.
String kebab(String camel) =>
    camel.replaceAllMapped(RegExp(r'(?<=[a-z0-9])(?=[A-Z])'), (_) => '-').toLowerCase();

const _fallbackStacks = {
  'JetBrainsMono': "ui-monospace, 'SF Mono', Menlo, Consolas, monospace",
  'PlayfairDisplay': "Georgia, 'Times New Roman', serif",
};

/// The full stylesheet: `@font-face` rules, color and type custom properties,
/// and one `.t-<style>` utility class per text style.
String buildTokensCss({
  required List<ColorToken> colors,
  required List<TypeToken> type,
  required List<FontFace> fonts,
  String fontDir = 'fonts',
}) {
  final out = StringBuffer()
    ..writeln('/* GENERATED by tool/site/build.dart from lib/core/theme/. Do not edit. */')
    ..writeln();

  for (final f in fonts) {
    out
      ..writeln('@font-face {')
      ..writeln("  font-family: '${f.family}';")
      ..writeln("  src: url('$fontDir/${f.fileName}') format('truetype');")
      ..writeln('  font-weight: ${f.weight};')
      ..writeln('  font-style: normal;')
      ..writeln('  font-display: swap;')
      ..writeln('}');
  }

  out
    ..writeln()
    ..writeln(':root {');
  for (final family in {for (final f in fonts) f.family, for (final t in type) t.family}) {
    final fallback = _fallbackStacks[family] ?? 'system-ui, -apple-system, sans-serif';
    out.writeln("  --font-${kebab(family)}: '$family', $fallback;");
  }
  for (final c in colors) {
    out
      ..writeln('  --${kebab(c.name)}: ${c.css};')
      ..writeln('  --${kebab(c.name)}-rgb: ${c.red}, ${c.green}, ${c.blue};');
  }
  for (final t in type) {
    final p = '--t-${kebab(t.name)}';
    out
      ..writeln('  $p-family: var(--font-${kebab(t.family)});')
      ..writeln('  $p-size: ${_trim(t.size, 2)}px;')
      ..writeln('  $p-weight: ${t.weight};')
      ..writeln('  $p-line-height: ${t.height == null ? 'normal' : _trim(t.height!, 3)};')
      ..writeln('  $p-tracking: ${_trim(t.size == 0 ? 0 : t.letterSpacing / t.size, 3)}em;');
  }
  out
    ..writeln('}')
    ..writeln();

  for (final t in type) {
    final p = '--t-${kebab(t.name)}';
    out
      ..writeln('.t-${kebab(t.name)} {')
      ..writeln('  font-family: var($p-family);')
      ..writeln('  font-size: var($p-size);')
      ..writeln('  font-weight: var($p-weight);')
      ..writeln('  line-height: var($p-line-height);')
      ..writeln('  letter-spacing: var($p-tracking);');
    if (t.tabularFigures) out.writeln('  font-variant-numeric: tabular-nums;');
    out.writeln('}');
  }
  return out.toString();
}

/// Custom property names defined by [css] (`--name:` declarations).
Set<String> definedCustomProperties(String css) =>
    {for (final m in RegExp(r'(--[\w-]+)\s*:').allMatches(css)) m.group(1)!};

String _trim(double value, int digits) {
  var s = value.toStringAsFixed(digits);
  if (s.contains('.')) s = s.replaceFirst(RegExp(r'\.?0+$'), '');
  return s == '-0' ? '0' : s;
}
